name: Security Audit
on:
  schedule:
    - cron:  '0 6 * * *'
  push:
    branches: [ trunk ]
  pull_request:
    branches: [ trunk ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install audit
      run: cargo install cargo-audit
    - name: Audit
      run: cargo audit
