on:
  push:
    tags:
      - 'v*' 

name: Rust Release

jobs:
  build:
    name: Build Release Linux
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@master
      - name: Run the tests
        run: cargo test
      - name: Build
        run: cargo build --release && mv ./target/release/aws-profile-vault ./target/release/aws-profile-vault-linux-x86_64
      - name: Share artefact with Upload job
        uses: actions/upload-artifact@v1
        with:
          name: aws-profile-vault-linux-x86_64
          path: ./target/release/aws-profile-vault-linux-x86_64

  upload:
    name: Upload Artefacts
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Grab Linux artefact for Release
        uses: actions/download-artifact@v1
        with:
          name: aws-profile-vault-linux-x86_64
      - name: Create Release
        id: create_release
        uses: actions/create-release@latest
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          draft: false
          prerelease: false
      - name: Upload Release Asset
        id: upload-release-asset 
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }} 
          asset_path: ./aws-profile-vault-linux-x86_64
          asset_name: aws-profile-vault-linux-x86_64
          asset_content_type: application/octet-stream
